In [1]:
import pandas as pd

happiness_df = pd.read_excel("Happiness_Report_2022.xls", usecols=["RANK", "Country", "Happiness score"])
happiness_df.columns = [col_name.lower().replace(" ", "_") for col_name in happiness_df.columns]
happiness_df = happiness_df.rename(columns={"happiness_score": "score"})[["country", "rank", "score"]]
happiness_df.head()

       country  rank   score
0      Finland     1  7.8210
1      Denmark     2  7.6362
2      Iceland     3  7.5575
3  Switzerland     4  7.5116
4  Netherlands     5  7.4149

In [2]:
happiness_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  147 non-null    object
 1   rank     147 non-null    int64
 2   score    146 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 3.6+ KB

In [3]:
sorted(happiness_df["country"])

['Afghanistan',
 'Albania',
 'Algeria',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan*',
 'Bahrain',
 'Bangladesh',
 'Belarus*',
 'Belgium',
 'Benin',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana*',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Chad*',
 'Chile',
 'China',
 'Colombia',
 'Comoros*',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Estonia',
 'Eswatini, Kingdom of*',
 'Ethiopia',
 'Finland',
 'France',
 'Gabon',
 'Gambia*',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala*',
 'Guinea',
 'Honduras',
 'Hong Kong S.A.R. of China',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait*',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho*',
 'Liberia*',
 'Libya*',
 'Lithuania',
 'Luxembourg*',
 'Madagascar*',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritania*',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger*',
 'Nigeria',
 'North Cyprus*',
 'North Macedonia',
 'Norway',
 'Pakistan',
 'Palestinian Territories*',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Romania',
 'Russia',
 'Rwanda*',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sweden',
 'Switzerland',
 'Taiwan Province of China',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tunisia',
 'Turkey',
 'Turkmenistan*',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Yemen*',
 'Zambia',
 'Zimbabwe',
 'xx']

In [4]:
happiness_df["country"] = happiness_df["country"].str.strip("*")
sorted(happiness_df["country"])

['Afghanistan',
 'Albania',
 'Algeria',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Benin',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Estonia',
 'Eswatini, Kingdom of',
 'Ethiopia',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Guinea',
 'Honduras',
 'Hong Kong S.A.R. of China',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Cyprus',
 'North Macedonia',
 'Norway',
 'Pakistan',
 'Palestinian Territories',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Romania',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sweden',
 'Switzerland',
 'Taiwan Province of China',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 'xx']

In [5]:
# happiness_df["country"] = happiness_df["country"].map({"United States": "United States of America"}, na_action="ignore")

In [6]:
happiness_df.to_parquet("happiness_rank_score_by_country_2022.parquet")

Source: https://worldhappiness.report/ed/2022/#appendices-and-data

In [7]:
import json

with open("all_countries.geo.json") as f:
    countries_polygons = f.read()

Source: https://geojson-maps.ash.ms/

In [8]:
sum(f'"name":"{country}"' not in countries_polygons for country in happiness_df["country"])

11

In [9]:
[country for country in happiness_df["country"] if f'"name":"{country}"' not in countries_polygons]

['United States',
 'Taiwan Province of China',
 'Mauritius',
 'Bosnia and Herzegovina',
 'Dominican Republic',
 'North Cyprus',
 'Hong Kong S.A.R. of China',
 'Ivory Coast',
 'Palestinian Territories',
 'Eswatini, Kingdom of',
 'xx']